// 声明proto的版本 只有 proto3 才支持 gRPC

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/spider.proto

// 指定当前proto文件属于helloworld包

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 具体的参数定义
type SpiderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 要请求的地址
	Method  string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // 请求方式
}

func (x *SpiderRequest) Reset() {
	*x = SpiderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderRequest) ProtoMessage() {}

func (x *SpiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderRequest.ProtoReflect.Descriptor instead.
func (*SpiderRequest) Descriptor() ([]byte, []int) {
	return file_proto_spider_proto_rawDescGZIP(), []int{0}
}

func (x *SpiderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SpiderRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type SpiderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpCode int32  `protobuf:"varint,1,opt,name=httpCode,proto3" json:"httpCode,omitempty"` // http状态码
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`  // 返回体
}

func (x *SpiderResponse) Reset() {
	*x = SpiderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderResponse) ProtoMessage() {}

func (x *SpiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderResponse.ProtoReflect.Descriptor instead.
func (*SpiderResponse) Descriptor() ([]byte, []int) {
	return file_proto_spider_proto_rawDescGZIP(), []int{1}
}

func (x *SpiderResponse) GetHttpCode() int32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

func (x *SpiderResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_spider_proto protoreflect.FileDescriptor

var file_proto_spider_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0d,
	0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22,
	0x48, 0x0a, 0x0e, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4f, 0x0a, 0x06, 0x53, 0x70, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x70, 0x69, 0x64,
	0x65, 0x72, 0x2e, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spider_proto_rawDescOnce sync.Once
	file_proto_spider_proto_rawDescData = file_proto_spider_proto_rawDesc
)

func file_proto_spider_proto_rawDescGZIP() []byte {
	file_proto_spider_proto_rawDescOnce.Do(func() {
		file_proto_spider_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spider_proto_rawDescData)
	})
	return file_proto_spider_proto_rawDescData
}

var file_proto_spider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_spider_proto_goTypes = []interface{}{
	(*SpiderRequest)(nil),  // 0: spider.SpiderRequest
	(*SpiderResponse)(nil), // 1: spider.SpiderResponse
}
var file_proto_spider_proto_depIdxs = []int32{
	0, // 0: spider.Spider.GetAddressResponse:input_type -> spider.SpiderRequest
	1, // 1: spider.Spider.GetAddressResponse:output_type -> spider.SpiderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_spider_proto_init() }
func file_proto_spider_proto_init() {
	if File_proto_spider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpiderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpiderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spider_proto_goTypes,
		DependencyIndexes: file_proto_spider_proto_depIdxs,
		MessageInfos:      file_proto_spider_proto_msgTypes,
	}.Build()
	File_proto_spider_proto = out.File
	file_proto_spider_proto_rawDesc = nil
	file_proto_spider_proto_goTypes = nil
	file_proto_spider_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpiderClient is the client API for Spider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpiderClient interface {
	// 该服务包含一个 SayHello 方法 HelloRequest、HelloReply分别为该方法的输入与输出
	GetAddressResponse(ctx context.Context, in *SpiderRequest, opts ...grpc.CallOption) (*SpiderResponse, error)
}

type spiderClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderClient(cc grpc.ClientConnInterface) SpiderClient {
	return &spiderClient{cc}
}

func (c *spiderClient) GetAddressResponse(ctx context.Context, in *SpiderRequest, opts ...grpc.CallOption) (*SpiderResponse, error) {
	out := new(SpiderResponse)
	err := c.cc.Invoke(ctx, "/spider.Spider/GetAddressResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServer is the server API for Spider service.
type SpiderServer interface {
	// 该服务包含一个 SayHello 方法 HelloRequest、HelloReply分别为该方法的输入与输出
	GetAddressResponse(context.Context, *SpiderRequest) (*SpiderResponse, error)
}

// UnimplementedSpiderServer can be embedded to have forward compatible implementations.
type UnimplementedSpiderServer struct {
}

func (*UnimplementedSpiderServer) GetAddressResponse(context.Context, *SpiderRequest) (*SpiderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressResponse not implemented")
}

func RegisterSpiderServer(s *grpc.Server, srv SpiderServer) {
	s.RegisterService(&_Spider_serviceDesc, srv)
}

func _Spider_GetAddressResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetAddressResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spider.Spider/GetAddressResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetAddressResponse(ctx, req.(*SpiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Spider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spider.Spider",
	HandlerType: (*SpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddressResponse",
			Handler:    _Spider_GetAddressResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spider.proto",
}
